#!/bin/bash

function usage {
  echo "KDED Orientation Helper Arguments"
  echo "-o | --output : A display name like eDP-1 (primary display is used by default)"
  echo "-r | --rotation : normal, inverted, left-up, right-up"
  echo "-h | --help : Arguments help"
  exit 1
}

while [ "$1" != "" ]; do
  case $1 in
    -o | --output )           shift
                              PRIMARY_DISPLAY=$1
                              ;;
    -r | --rotation )         shift
                              ROTATION=$1
                              ;;
    -h | --help )
                              usage
                              ;;
    * )
                              usage
  esac
  shift
done

if [ -z "$ROTATION" ]; then
  usage
fi

if [ "$ROTATION" == "normal" ]; then
  kscreen-doctor output.1.rotation.normal
elif [ "$ROTATION" == "bottom-up" ]; then
  kscreen-doctor output.1.rotation.inverted
elif [ "$ROTATION" == "left-up" ]; then
  kscreen-doctor output.1.rotation.left
elif [ "$ROTATION" == "right-up" ]; then
  kscreen-doctor output.1.rotation.right
fi
